<?php



$googlefonts = array(
	'Abel' => 'Abel', 
	'Abril+Fatface' => 'Abril Fatface', 
	'Aclonica' => 'Aclonica', 
	'Acme' => 'Acme', 
	'Actor' => 'Actor', 
	'Adamina' => 'Adamina', 
	'Advent+Pro:100,400,200,300,500,600,700' => 'Advent Pro', 
	'Aguafina+Script' => 'Aguafina Script', 
	'Aladin' => 'Aladin', 
	'Aldrich' => 'Aldrich', 
	'Alegreya:italic,400,700,700italic,900,900italic' => 'Alegreya', 
	'Alegreya+SC:italic,400,700,700italic,900,900italic' => 'Alegreya SC', 
	'Alex+Brush' => 'Alex Brush', 
	'Alfa+Slab+One' => 'Alfa Slab One', 
	'Alice' => 'Alice', 
	'Alike' => 'Alike', 
	'Alike+Angular' => 'Alike Angular', 
	'Allan:700,400' => 'Allan', 
	'Allerta' => 'Allerta', 
	'Allerta+Stencil' => 'Allerta Stencil', 
	'Allura' => 'Allura', 
	'Almendra:italic,400,700' => 'Almendra', 
	'Almendra+SC' => 'Almendra SC', 
	'Amaranth:italic,400,700,700italic' => 'Amaranth', 
	'Amatic+SC:700,400' => 'Amatic SC', 
	'Amethysta' => 'Amethysta', 
	'Andada' => 'Andada', 
	'Andika' => 'Andika', 
	'Angkor' => 'Angkor', 
	'Annie+Use+Your+Telescope' => 'Annie Use Your Telescope', 
	'Anonymous+Pro:italic,400,700,700italic' => 'Anonymous Pro', 
	'Antic' => 'Antic', 
	'Antic+Didone' => 'Antic Didone', 
	'Antic+Slab' => 'Antic Slab', 
	'Anton' => 'Anton', 
	'Arapey:italic,400' => 'Arapey', 
	'Arbutus' => 'Arbutus', 
	'Architects+Daughter' => 'Architects Daughter', 
	'Arimo:italic,400,700,700italic' => 'Arimo', 
	'Arizonia' => 'Arizonia', 
	'Armata' => 'Armata', 
	'Artifika' => 'Artifika', 
	'Arvo:italic,400,700,700italic' => 'Arvo', 
	'Asap:italic,400,700,700italic' => 'Asap', 
	'Asset' => 'Asset', 
	'Astloch:700,400' => 'Astloch', 
	'Asul:700,400' => 'Asul', 
	'Atomic+Age' => 'Atomic Age', 
	'Aubrey' => 'Aubrey', 
	'Audiowide' => 'Audiowide', 
	'Average' => 'Average', 
	'Averia+Gruesa+Libre' => 'Averia Gruesa Libre', 
	'Averia+Libre:300,400,300italic,italic,700,700italic' => 'Averia Libre', 
	'Averia+Sans+Libre:300,400,300italic,italic,700,700italic' => 'Averia Sans Libre', 
	'Averia+Serif+Libre:300,400,300italic,italic,700,700italic' => 'Averia Serif Libre', 
	'Bad+Script' => 'Bad Script', 
	'Balthazar' => 'Balthazar', 
	'Bangers' => 'Bangers', 
	'Basic' => 'Basic', 
	'Battambang:700,400' => 'Battambang', 
	'Baumans' => 'Baumans', 
	'Bayon' => 'Bayon', 
	'Belgrano' => 'Belgrano', 
	'Belleza' => 'Belleza', 
	'Bentham' => 'Bentham', 
	'Berkshire+Swash' => 'Berkshire Swash', 
	'Bevan' => 'Bevan', 
	'Bigshot+One' => 'Bigshot One', 
	'Bilbo' => 'Bilbo', 
	'Bilbo+Swash+Caps' => 'Bilbo Swash Caps', 
	'Bitter:italic,400,700' => 'Bitter', 
	'Black+Ops+One' => 'Black Ops One', 
	'Bokor' => 'Bokor', 
	'Bonbon' => 'Bonbon', 
	'Boogaloo' => 'Boogaloo', 
	'Bowlby+One' => 'Bowlby One', 
	'Bowlby+One+SC' => 'Bowlby One SC', 
	'Brawler' => 'Brawler', 
	'Bree+Serif' => 'Bree Serif', 
	'Bubblegum+Sans' => 'Bubblegum Sans', 
	'Buda:300,400' => 'Buda', 
	'Buenard:700,400' => 'Buenard', 
	'Butcherman' => 'Butcherman', 
	'Butterfly+Kids' => 'Butterfly Kids', 
	'Cabin:italic,400,500,500italic,600,600italic,700,700italic' => 'Cabin', 
	'Cabin+Condensed:500,400,600,700' => 'Cabin Condensed', 
	'Cabin+Sketch:700,400' => 'Cabin Sketch', 
	'Caesar+Dressing' => 'Caesar Dressing', 
	'Cagliostro' => 'Cagliostro', 
	'Calligraffitti' => 'Calligraffitti', 
	'Cambo' => 'Cambo', 
	'Candal' => 'Candal', 
	'Cantarell:italic,400,700,700italic' => 'Cantarell', 
	'Cantata+One' => 'Cantata One', 
	'Cardo:italic,400,700' => 'Cardo', 
	'Carme' => 'Carme', 
	'Carter+One' => 'Carter One', 
	'Caudex:italic,400,700,700italic' => 'Caudex', 
	'Cedarville+Cursive' => 'Cedarville Cursive', 
	'Ceviche+One' => 'Ceviche One', 
	'Changa+One:italic,400' => 'Changa One', 
	'Chango' => 'Chango', 
	'Chau+Philomene+One:italic,400' => 'Chau Philomene One', 
	'Chelsea+Market' => 'Chelsea Market', 
	'Chenla' => 'Chenla', 
	'Cherry+Cream+Soda' => 'Cherry Cream Soda', 
	'Chewy' => 'Chewy', 
	'Chicle' => 'Chicle', 
	'Chivo:italic,400,900,900italic' => 'Chivo', 
	'Coda:800,400' => 'Coda', 
	'Coda+Caption:800,400' => 'Coda Caption', 
	'Codystar:300,400' => 'Codystar', 
	'Comfortaa:300,400,700' => 'Comfortaa', 
	'Coming+Soon' => 'Coming Soon', 
	'Concert+One' => 'Concert One', 
	'Condiment' => 'Condiment', 
	'Content:700,400' => 'Content', 
	'Contrail+One' => 'Contrail One', 
	'Convergence' => 'Convergence', 
	'Cookie' => 'Cookie', 
	'Copse' => 'Copse', 
	'Corben:700,400' => 'Corben', 
	'Cousine:italic,400,700,700italic' => 'Cousine', 
	'Coustard:900,400' => 'Coustard', 
	'Covered+By+Your+Grace' => 'Covered By Your Grace', 
	'Crafty+Girls' => 'Crafty Girls', 
	'Creepster' => 'Creepster', 
	'Crete+Round:italic,400' => 'Crete Round', 
	'Crimson+Text:italic,400,600,600italic,700,700italic' => 'Crimson Text', 
	'Crushed' => 'Crushed', 
	'Cuprum:italic,400,700,700italic' => 'Cuprum', 
	'Cutive' => 'Cutive', 
	'Damion' => 'Damion', 
	'Dancing+Script:700,400' => 'Dancing Script', 
	'Dangrek' => 'Dangrek', 
	'Dawning+of+a+New+Day' => 'Dawning of a New Day', 
	'Days+One' => 'Days One', 
	'Delius' => 'Delius', 
	'Delius+Swash+Caps' => 'Delius Swash Caps', 
	'Delius+Unicase:700,400' => 'Delius Unicase', 
	'Della+Respira' => 'Della Respira', 
	'Devonshire' => 'Devonshire', 
	'Didact+Gothic' => 'Didact Gothic', 
	'Diplomata' => 'Diplomata', 
	'Diplomata+SC' => 'Diplomata SC', 
	'Doppio+One' => 'Doppio One', 
	'Dorsa' => 'Dorsa', 
	'Dosis:200,400,300,500,600,700,800' => 'Dosis', 
	'Dr+Sugiyama' => 'Dr Sugiyama', 
	'Droid+Sans:700,400' => 'Droid Sans', 
	'Droid+Sans+Mono' => 'Droid Sans Mono', 
	'Droid+Serif:italic,400,700,700italic' => 'Droid Serif', 
	'Duru+Sans' => 'Duru Sans', 
	'Dynalight' => 'Dynalight', 
	'EB+Garamond' => 'EB Garamond', 
	'Eater' => 'Eater', 
	'Economica:italic,400,700,700italic' => 'Economica', 
	'Electrolize' => 'Electrolize', 
	'Emblema+One' => 'Emblema One', 
	'Emilys+Candy' => 'Emilys Candy', 
	'Engagement' => 'Engagement', 
	'Enriqueta:700,400' => 'Enriqueta', 
	'Erica+One' => 'Erica One', 
	'Esteban' => 'Esteban', 
	'Euphoria+Script' => 'Euphoria Script', 
	'Ewert' => 'Ewert', 
	'Exo:100,400,100italic,200,200italic,300,300italic,italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic' => 'Exo', 
	'Expletus+Sans:italic,400,500,500italic,600,600italic,700,700italic' => 'Expletus Sans', 
	'Fanwood+Text:italic,400' => 'Fanwood Text', 
	'Fascinate' => 'Fascinate', 
	'Fascinate+Inline' => 'Fascinate Inline', 
	'Federant' => 'Federant', 
	'Federo' => 'Federo', 
	'Felipa' => 'Felipa', 
	'Fjord+One' => 'Fjord One', 
	'Flamenco:300,400' => 'Flamenco', 
	'Flavors' => 'Flavors', 
	'Fondamento:italic,400' => 'Fondamento', 
	'Fontdiner+Swanky' => 'Fontdiner Swanky', 
	'Forum' => 'Forum', 
	'Francois+One' => 'Francois One', 
	'Fredericka+the+Great' => 'Fredericka the Great', 
	'Fredoka+One' => 'Fredoka One', 
	'Freehand' => 'Freehand', 
	'Fresca' => 'Fresca', 
	'Frijole' => 'Frijole', 
	'Fugaz+One' => 'Fugaz One', 
	'GFS+Didot' => 'GFS Didot', 
	'GFS+Neohellenic:italic,400,700,700italic' => 'GFS Neohellenic', 
	'Galdeano' => 'Galdeano', 
	'Gentium+Basic:italic,400,700,700italic' => 'Gentium Basic', 
	'Gentium+Book+Basic:italic,400,700,700italic' => 'Gentium Book Basic', 
	'Geo' => 'Geo', 
	'Geostar' => 'Geostar', 
	'Geostar+Fill' => 'Geostar Fill', 
	'Germania+One' => 'Germania One', 
	'Give+You+Glory' => 'Give You Glory', 
	'Glass+Antiqua' => 'Glass Antiqua', 
	'Glegoo' => 'Glegoo', 
	'Gloria+Hallelujah' => 'Gloria Hallelujah', 
	'Goblin+One' => 'Goblin One', 
	'Gochi+Hand' => 'Gochi Hand', 
	'Gorditas:700,400' => 'Gorditas', 
	'Goudy+Bookletter+1911' => 'Goudy Bookletter 1911', 
	'Graduate' => 'Graduate', 
	'Gravitas+One' => 'Gravitas One', 
	'Great+Vibes' => 'Great Vibes', 
	'Gruppo' => 'Gruppo', 
	'Gudea:italic,400,700' => 'Gudea', 
	'Habibi' => 'Habibi', 
	'Hammersmith+One' => 'Hammersmith One', 
	'Handlee' => 'Handlee', 
	'Hanuman:700,400' => 'Hanuman', 
	'Happy+Monkey' => 'Happy Monkey', 
	'Henny+Penny' => 'Henny Penny', 
	'Herr+Von+Muellerhoff' => 'Herr Von Muellerhoff', 
	'Holtwood+One+SC' => 'Holtwood One SC', 
	'Homemade+Apple' => 'Homemade Apple', 
	'Homenaje' => 'Homenaje', 
	'IM+Fell+DW+Pica:italic,400' => 'IM Fell DW Pica', 
	'IM+Fell+DW+Pica+SC' => 'IM Fell DW Pica SC', 
	'IM+Fell+Double+Pica:italic,400' => 'IM Fell Double Pica', 
	'IM+Fell+Double+Pica+SC' => 'IM Fell Double Pica SC', 
	'IM+Fell+English:italic,400' => 'IM Fell English', 
	'IM+Fell+English+SC' => 'IM Fell English SC', 
	'IM+Fell+French+Canon:italic,400' => 'IM Fell French Canon', 
	'IM+Fell+French+Canon+SC' => 'IM Fell French Canon SC', 
	'IM+Fell+Great+Primer:italic,400' => 'IM Fell Great Primer', 
	'IM+Fell+Great+Primer+SC' => 'IM Fell Great Primer SC', 
	'Iceberg' => 'Iceberg', 
	'Iceland' => 'Iceland', 
	'Imprima' => 'Imprima', 
	'Inconsolata' => 'Inconsolata', 
	'Inder' => 'Inder', 
	'Indie+Flower' => 'Indie Flower', 
	'Inika:700,400' => 'Inika', 
	'Irish+Grover' => 'Irish Grover', 
	'Istok+Web:italic,400,700,700italic' => 'Istok Web', 
	'Italiana' => 'Italiana', 
	'Italianno' => 'Italianno', 
	'Jim+Nightshade' => 'Jim Nightshade', 
	'Jockey+One' => 'Jockey One', 
	'Jolly+Lodger' => 'Jolly Lodger', 
	'Josefin+Sans:100,400,100italic,300,300italic,italic,600,600italic,700,700italic' => 'Josefin Sans', 
	'Josefin+Slab:100,400,100italic,300,300italic,italic,600,600italic,700,700italic' => 'Josefin Slab', 
	'Judson:italic,400,700' => 'Judson', 
	'Julee' => 'Julee', 
	'Junge' => 'Junge', 
	'Jura:300,400,500,600' => 'Jura', 
	'Just+Another+Hand' => 'Just Another Hand', 
	'Just+Me+Again+Down+Here' => 'Just Me Again Down Here', 
	'Kameron:700,400' => 'Kameron', 
	'Karla:italic,400,700,700italic' => 'Karla', 
	'Kaushan+Script' => 'Kaushan Script', 
	'Kelly+Slab' => 'Kelly Slab', 
	'Kenia' => 'Kenia', 
	'Khmer' => 'Khmer', 
	'Knewave' => 'Knewave', 
	'Kotta+One' => 'Kotta One', 
	'Koulen' => 'Koulen', 
	'Kranky' => 'Kranky', 
	'Kreon:300,400,700' => 'Kreon', 
	'Kristi' => 'Kristi', 
	'Krona+One' => 'Krona One', 
	'La+Belle+Aurore' => 'La Belle Aurore', 
	'Lancelot' => 'Lancelot', 
	'Lato:100,400,100italic,300,300italic,italic,700,700italic,900,900italic' => 'Lato', 
	'League+Script' => 'League Script', 
	'Leckerli+One' => 'Leckerli One', 
	'Ledger' => 'Ledger', 
	'Lekton:italic,400,700' => 'Lekton', 
	'Lemon' => 'Lemon', 
	'Lilita+One' => 'Lilita One', 
	'Limelight' => 'Limelight', 
	'Linden+Hill:italic,400' => 'Linden Hill', 
	'Lobster' => 'Lobster', 
	'Lobster+Two:italic,400,700,700italic' => 'Lobster Two', 
	'Londrina+Outline' => 'Londrina Outline', 
	'Londrina+Shadow' => 'Londrina Shadow', 
	'Londrina+Sketch' => 'Londrina Sketch', 
	'Londrina+Solid' => 'Londrina Solid', 
	'Lora:italic,400,700,700italic' => 'Lora', 
	'Love+Ya+Like+A+Sister' => 'Love Ya Like A Sister', 
	'Loved+by+the+King' => 'Loved by the King', 
	'Lovers+Quarrel' => 'Lovers Quarrel', 
	'Luckiest+Guy' => 'Luckiest Guy', 
	'Lusitana:700,400' => 'Lusitana', 
	'Lustria' => 'Lustria', 
	'Macondo' => 'Macondo', 
	'Macondo+Swash+Caps' => 'Macondo Swash Caps', 
	'Magra:700,400' => 'Magra', 
	'Maiden+Orange' => 'Maiden Orange', 
	'Mako' => 'Mako', 
	'Marck+Script' => 'Marck Script', 
	'Marko+One' => 'Marko One', 
	'Marmelad' => 'Marmelad', 
	'Marvel:italic,400,700,700italic' => 'Marvel', 
	'Mate:italic,400' => 'Mate', 
	'Mate+SC' => 'Mate SC', 
	'Maven+Pro:500,400,700,900' => 'Maven Pro', 
	'Meddon' => 'Meddon', 
	'MedievalSharp' => 'MedievalSharp', 
	'Medula+One' => 'Medula One', 
	'Megrim' => 'Megrim', 
	'Merienda+One' => 'Merienda One', 
	'Merriweather:300,400,700,900' => 'Merriweather', 
	'Metal' => 'Metal', 
	'Metamorphous' => 'Metamorphous', 
	'Metrophobic' => 'Metrophobic', 
	'Michroma' => 'Michroma', 
	'Miltonian' => 'Miltonian', 
	'Miltonian+Tattoo' => 'Miltonian Tattoo', 
	'Miniver' => 'Miniver', 
	'Miss+Fajardose' => 'Miss Fajardose', 
	'Modern+Antiqua' => 'Modern Antiqua', 
	'Molengo' => 'Molengo', 
	'Monofett' => 'Monofett', 
	'Monoton' => 'Monoton', 
	'Monsieur+La+Doulaise' => 'Monsieur La Doulaise', 
	'Montaga' => 'Montaga', 
	'Montez' => 'Montez', 
	'Montserrat' => 'Montserrat', 
	'Moul' => 'Moul', 
	'Moulpali' => 'Moulpali', 
	'Mountains+of+Christmas:700,400' => 'Mountains of Christmas', 
	'Mr+Bedfort' => 'Mr Bedfort', 
	'Mr+Dafoe' => 'Mr Dafoe', 
	'Mr+De+Haviland' => 'Mr De Haviland', 
	'Mrs+Saint+Delafield' => 'Mrs Saint Delafield', 
	'Mrs+Sheppards' => 'Mrs Sheppards', 
	'Muli:300,400,300italic,italic' => 'Muli', 
	'Mystery+Quest' => 'Mystery Quest', 
	'Neucha' => 'Neucha', 
	'Neuton:200,400,300,italic,700,800' => 'Neuton', 
	'News+Cycle:700,400' => 'News Cycle', 
	'Niconne' => 'Niconne', 
	'Nixie+One' => 'Nixie One', 
	'Nobile:italic,400,700,700italic' => 'Nobile', 
	'Nokora:700,400' => 'Nokora', 
	'Norican' => 'Norican', 
	'Nosifer' => 'Nosifer', 
	'Nothing+You+Could+Do' => 'Nothing You Could Do', 
	'Noticia+Text:italic,400,700,700italic' => 'Noticia Text', 
	'Nova+Cut' => 'Nova Cut', 
	'Nova+Flat' => 'Nova Flat', 
	'Nova+Mono' => 'Nova Mono', 
	'Nova+Oval' => 'Nova Oval', 
	'Nova+Round' => 'Nova Round', 
	'Nova+Script' => 'Nova Script', 
	'Nova+Slim' => 'Nova Slim', 
	'Nova+Square' => 'Nova Square', 
	'Numans' => 'Numans', 
	'Nunito:300,400,700' => 'Nunito', 
	'Odor+Mean+Chey' => 'Odor Mean Chey', 
	'Old+Standard+TT:italic,400,700' => 'Old Standard TT', 
	'Oldenburg' => 'Oldenburg', 
	'Oleo+Script:700,400' => 'Oleo Script', 
	'Open+Sans:300,400,300italic,italic,600,600italic,700,700italic,800,800italic' => 'Open Sans', 
	'Open+Sans+Condensed:300,400,300italic,700' => 'Open Sans Condensed', 
	'Orbitron:500,400,700,900' => 'Orbitron', 
	'Original+Surfer' => 'Original Surfer', 
	'Oswald:300,400,700' => 'Oswald', 
	'Over+the+Rainbow' => 'Over the Rainbow', 
	'Overlock:italic,400,700,700italic,900,900italic' => 'Overlock', 
	'Overlock+SC' => 'Overlock SC', 
	'Ovo' => 'Ovo', 
	'Oxygen' => 'Oxygen', 
	'PT+Mono' => 'PT Mono', 
	'PT+Sans:italic,400,700,700italic' => 'PT Sans', 
	'PT+Sans+Caption:700,400' => 'PT Sans Caption', 
	'PT+Sans+Narrow:700,400' => 'PT Sans Narrow', 
	'PT+Serif:italic,400,700,700italic' => 'PT Serif', 
	'PT+Serif+Caption:italic,400' => 'PT Serif Caption', 
	'Pacifico' => 'Pacifico', 
	'Parisienne' => 'Parisienne', 
	'Passero+One' => 'Passero One', 
	'Passion+One:700,400,900' => 'Passion One', 
	'Patrick+Hand' => 'Patrick Hand', 
	'Patua+One' => 'Patua One', 
	'Paytone+One' => 'Paytone One', 
	'Permanent+Marker' => 'Permanent Marker', 
	'Petrona' => 'Petrona', 
	'Philosopher:italic,400,700,700italic' => 'Philosopher', 
	'Piedra' => 'Piedra', 
	'Pinyon+Script' => 'Pinyon Script', 
	'Plaster' => 'Plaster', 
	'Play:700,400' => 'Play', 
	'Playball' => 'Playball', 
	'Playfair+Display:italic,400' => 'Playfair Display', 
	'Podkova:700,400' => 'Podkova', 
	'Poiret+One' => 'Poiret One', 
	'Poller+One' => 'Poller One', 
	'Poly:italic,400' => 'Poly', 
	'Pompiere' => 'Pompiere', 
	'Pontano+Sans' => 'Pontano Sans', 
	'Port+Lligat+Sans' => 'Port Lligat Sans', 
	'Port+Lligat+Slab' => 'Port Lligat Slab', 
	'Prata' => 'Prata', 
	'Preahvihear' => 'Preahvihear', 
	'Press+Start+2P' => 'Press Start 2P', 
	'Princess+Sofia' => 'Princess Sofia', 
	'Prociono' => 'Prociono', 
	'Prosto+One' => 'Prosto One', 
	'Puritan:italic,400,700,700italic' => 'Puritan', 
	'Quantico:italic,400,700,700italic' => 'Quantico', 
	'Quattrocento:700,400' => 'Quattrocento', 
	'Quattrocento+Sans:italic,400,700,700italic' => 'Quattrocento Sans', 
	'Questrial' => 'Questrial', 
	'Quicksand:300,400,700' => 'Quicksand', 
	'Qwigley' => 'Qwigley', 
	'Radley:italic,400' => 'Radley', 
	'Raleway:100,400' => 'Raleway', 
	'Rambla:400,700,400italic,700italic' => 'Rambla', 
	'Rammetto+One' => 'Rammetto One', 
	'Rancho' => 'Rancho', 
	'Rationale' => 'Rationale', 
	'Redressed' => 'Redressed', 
	'Reenie+Beanie' => 'Reenie Beanie', 
	'Revalia' => 'Revalia', 
	'Ribeye' => 'Ribeye', 
	'Ribeye+Marrow' => 'Ribeye Marrow', 
	'Righteous' => 'Righteous', 
	'Rochester' => 'Rochester', 
	'Rock+Salt' => 'Rock Salt', 
	'Rokkitt:700,400' => 'Rokkitt', 
	'Ropa+Sans:italic,400' => 'Ropa Sans', 
	'Rosario:italic,400,700,700italic' => 'Rosario', 
	'Rosarivo:italic,400' => 'Rosarivo', 
	'Rouge+Script' => 'Rouge Script', 
	'Ruda:700,400,900' => 'Ruda', 
	'Ruge+Boogie' => 'Ruge Boogie', 
	'Ruluko' => 'Ruluko', 
	'Ruslan+Display' => 'Ruslan Display', 
	'Russo+One' => 'Russo One', 
	'Ruthie' => 'Ruthie', 
	'Sail' => 'Sail', 
	'Salsa' => 'Salsa', 
	'Sancreek' => 'Sancreek', 
	'Sansita+One' => 'Sansita One', 
	'Sarina' => 'Sarina', 
	'Satisfy' => 'Satisfy', 
	'Schoolbell' => 'Schoolbell', 
	'Seaweed+Script' => 'Seaweed Script', 
	'Sevillana' => 'Sevillana', 
	'Shadows+Into+Light' => 'Shadows Into Light', 
	'Shadows+Into+Light+Two' => 'Shadows Into Light Two', 
	'Shanti' => 'Shanti', 
	'Share:italic,400,700,700italic' => 'Share', 
	'Shojumaru' => 'Shojumaru', 
	'Short+Stack' => 'Short Stack', 
	'Siemreap' => 'Siemreap', 
	'Sigmar+One' => 'Sigmar One', 
	'Signika:300,400,600,700' => 'Signika', 
	'Signika+Negative:300,400,600,700' => 'Signika Negative', 
	'Simonetta:italic,400,900,900italic' => 'Simonetta', 
	'Sirin+Stencil' => 'Sirin Stencil', 
	'Six+Caps' => 'Six Caps', 
	'Slackey' => 'Slackey', 
	'Smokum' => 'Smokum', 
	'Smythe' => 'Smythe', 
	'Sniglet:800,400' => 'Sniglet', 
	'Snippet' => 'Snippet', 
	'Sofia' => 'Sofia', 
	'Sonsie+One' => 'Sonsie One', 
	'Sorts+Mill+Goudy:italic,400' => 'Sorts Mill Goudy', 
	'Special+Elite' => 'Special Elite', 
	'Spicy+Rice' => 'Spicy Rice', 
	'Spinnaker' => 'Spinnaker', 
	'Spirax' => 'Spirax', 
	'Squada+One' => 'Squada One', 
	'Stardos+Stencil:700,400' => 'Stardos Stencil', 
	'Stint+Ultra+Condensed' => 'Stint Ultra Condensed', 
	'Stint+Ultra+Expanded' => 'Stint Ultra Expanded', 
	'Stoke' => 'Stoke', 
	'Strait' => 'Strait', 
	'Sue+Ellen+Francisco' => 'Sue Ellen Francisco', 
	'Sunshiney' => 'Sunshiney', 
	'Supermercado+One' => 'Supermercado One', 
	'Suwannaphum' => 'Suwannaphum', 
	'Swanky+and+Moo+Moo' => 'Swanky and Moo Moo', 
	'Syncopate:700,400' => 'Syncopate', 
	'Tangerine:700,400' => 'Tangerine', 
	'Taprom' => 'Taprom', 
	'Telex' => 'Telex', 
	'Tenor+Sans' => 'Tenor Sans', 
	'The+Girl+Next+Door' => 'The Girl Next Door', 
	'Tienne:700,400,900' => 'Tienne', 
	'Tinos:italic,400,700,700italic' => 'Tinos', 
	'Titan+One' => 'Titan One', 
	'Trade+Winds' => 'Trade Winds', 
	'Trocchi' => 'Trocchi', 
	'Trochut:italic,400,700' => 'Trochut', 
	'Trykker' => 'Trykker', 
	'Tulpen+One' => 'Tulpen One', 
	'Ubuntu:300,400,300italic,italic,500,500italic,700,700italic' => 'Ubuntu', 
	'Ubuntu+Condensed' => 'Ubuntu Condensed', 
	'Ubuntu+Mono:italic,400,700,700italic' => 'Ubuntu Mono', 
	'Ultra' => 'Ultra', 
	'Uncial+Antiqua' => 'Uncial Antiqua', 
	'UnifrakturCook:700,400' => 'UnifrakturCook', 
	'UnifrakturMaguntia' => 'UnifrakturMaguntia', 
	'Unkempt:700,400' => 'Unkempt', 
	'Unlock' => 'Unlock', 
	'Unna' => 'Unna', 
	'VT323' => 'VT323', 
	'Varela' => 'Varela', 
	'Varela+Round' => 'Varela Round', 
	'Vast+Shadow' => 'Vast Shadow', 
	'Vibur' => 'Vibur', 
	'Vidaloka' => 'Vidaloka', 
	'Viga' => 'Viga', 
	'Voces' => 'Voces', 
	'Volkhov:italic,400,700,700italic' => 'Volkhov', 
	'Vollkorn:italic,400,700,700italic' => 'Vollkorn', 
	'Voltaire' => 'Voltaire', 
	'Waiting+for+the+Sunrise' => 'Waiting for the Sunrise', 
	'Wallpoet' => 'Wallpoet', 
	'Walter+Turncoat' => 'Walter Turncoat', 
	'Wellfleet' => 'Wellfleet', 
	'Wire+One' => 'Wire One', 
	'Yanone+Kaffeesatz:200,400,300,700' => 'Yanone Kaffeesatz', 
	'Yellowtail' => 'Yellowtail', 
	'Yeseva+One' => 'Yeseva One', 
	'Yesteryear' => 'Yesteryear', 
	'Zeyada' => 'Zeyada',
);






// Font Size
$fontsizearray = array();
$fontsize  = range(5, 60);
foreach($fontsize as $size){
	$fontsizearray[$size] = $size.'px';
}





class ThemeCore {
    public static $main;
    public static $initialized = false;
            
    public static function autoloader($class) {
        if (strpos($class, 'ThemeWidget') === 0) {
            $filename = HONEY_PATH_TO_THEME_CODE_PHP.'/widgets/'.$class.'.php';
            require($filename);
            return true;
        } 
        if (strpos($class, 'ThemeMetabox') === 0) {
            $filename = HONEY_PATH_TO_THEME_CODE_PHP.'/metaboxes/'.$class.'.php';
            require($filename);
            return true;
        }        
        if (strpos($class, 'ThemeShortcode') === 0) {
            $filename = HONEY_PATH_TO_THEME_CODE_PHP.'/shortcodes/'.$class.'.php';
            require($filename);
            return true;
        }                
        elseif (file_exists(HONEY_PATH_TO_THEME_CODE_PHP."/$class.php")) {
            require(HONEY_PATH_TO_THEME_CODE_PHP."/$class.php");
            return true;
        }
        return false;
    }
    
    public static function init() {
        if (!ThemeCore::$initialized) {
            if (function_exists('spl_autoload_register')) {
                spl_autoload_register(array('ThemeCore', 'autoloader'));
            } else {
                function __autoload($class) {
                    ThemeCore::autoloader($class);
                }
            }
            ThemeCore::$initialized = true;
        }
        add_image_size('project-thumb', 230, 230, true);
        add_image_size('project-twocolumn', 480, 480, true);
        add_image_size('project-threecolumn', 313, 313, true);
        add_image_size('blog-classic', 701, 99999);
        add_image_size('blog-alternative', 313, 313, true);
        add_image_size('blog-thumb', 230, 115, true);
        
		// Setting WooCommerce image size
		if( function_exists( 'is_woocommerce' ) ){
			honey_woocommerce_image_dimensions();
		}
		
    }
}






function honey_woocommerce_image_dimensions(){
	$catalog = array(
		'width' 	=> '400',	// px
		'height'	=> '400',	// px
		'crop'		=> 1 		// true
	);

	$single = array(
		'width' 	=> '600',	// px
		'height'	=> '600',	// px
		'crop'		=> 1 		// true
	);

	$thumbnail = array(
		'width' 	=> '120',	// px
		'height'	=> '120',	// px
		'crop'		=> 0 		// false
	);

	// Image sizes
	update_option( 'shop_catalog_image_size', $catalog ); 		// Product category thumbs
	update_option( 'shop_single_image_size', $single ); 		// Single product image
	update_option( 'shop_thumbnail_image_size', $thumbnail ); 	// Image gallery thumbs
}